CREATE TABLE IF NOT EXISTS holdings (
  id SERIAL PRIMARY KEY,
  ticker VARCHAR(10) NOT NULL,
  shares INTEGER NOT NULL,
  avg_price NUMERIC(10,2) NOT NULL,
  sector VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
