services:
  client:
    image: emanmalik15/divigrow-app:notes-client
    build:
      context: ./client
      args:
        VITE_API_URL: http://13.62.55.158:5001/api
    container_name: divi_client
    ports:
      - "3000:80"
    depends_on:
      - app
    restart: always

  app:
    image: emanmalik15/divigrow-app:notes-server
    build:
      context: ./server
    container_name: divi_app_server
    ports:
      - "5001:4000"
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: divi_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      CORS_ORIGIN: http://13.62.55.158:3000
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: divi_app_db
    environment:
      POSTGRES_DB: divi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always

volumes:
  postgres_data: